### PR TITLE
Add ansible role by arbabnazar

### PR DESCRIPTION
**Pull request by arbabnazar**
@mfaure I tried to address all the comments that you have mentioned on the PR, kindly review and let me know if you have other comments. Thanks

### CODE REVIEW

**Comment by dzc34** [comment]
@mfaure you could use these command lines :
`git fetch origin`
`git checkout origin/add_ansible_role_by_arbabnazar`
`git checkout -b add_ansible_role_by_arbabnazar`
`git fetch origin refs/pull/50/head`
`git merge FETCH_HEAD`
`git rebase develop`

and you could use these command lines
for adding the log of commits in the merging commit
`git checkout develop` 
`git merge --log --no-ff add_ansible_role_by_arbabnazar`
`git push origin develop`

**Comment by mfaure** [comment]
@arbabnazar Thank you ! Your contrib has been merged. I made a few (typo) changes to the README.

@dzc34 I used your suggestion, it worked (but Github does not see the contrib has been merged).

Good work gentlemen, thank you very much. I close this PR.

**Comment by arbabnazar** [comment]
@mfaure do I need to add my name in any contributor list or that's all? Thanks

**Comment by mfaure** [comment]
@arbabnazar Everything is automatic. Once your code is merged in master, your name will appear in the contributors (poeple). [By now, two tasks remain to be done to merge: install doc review and logo integration, which should be done rather quickly :) ]

**Comment by arbabnazar** [comment]
@mfaure sorry I didn't understand for the tasks, they are ansible tasks? you want any changes in ansible role? Thanks

**Comment by mfaure** [comment]
@arbabnazar no no, it's not "ansible task", it is just things to be done

**Pull request closed without merging**
