### PR TITLE
pass host as variable in mysql_user module

### PR DESCRIPTION
**Pull request by arbabnazar**
@mfaure @jkowalczyk @dzc34 kindly review this minor change, but it's really helpful, if somebody want to use remote mysql. Thanks

### CODE REVIEW

**Comment by dzc34** [comment]
hi @arbabnazar,

your patch is now in the branch named "ansible_host_variable_in_mysql_conifg_by_arbabnazar"
https://github.com/Asqatasun/Asqatasun/commit/b674b0fc7b4f63ec2f21af1e02eb19562cb0c5ad

please, when you create a pull-request, make it on the branch named "develop"
or for this subject on the branch named "ansible_host_variable_in_mysql_conifg_by_arbabnazar"

if you want, you can add a star to the project... :)

Regards,

**Comment by arbabnazar** [comment]
@mfaure can you please review the following change. Thanks

**Comment by dzc34** [comment]
hi @arbabnazar,

your patch is now in the develop branch

**Comment by arbabnazar** [comment]
@dzc34 great. Thanks

**Comment by mfaure** [comment]
Hi @arbabnazar, thanks for your contrib ! It's been merged (sorry for the delay).

It is merged in `develop` branch as this is the branch everyone should work onto. (We tend to keep the `master` branch for release only, so that whenever you clone master, you can put it in production).

Thanks again !

**Pull request closed without merging**
