### PR TITLE
add the libtomcat7-java package

### PR DESCRIPTION
**Pull request by arbabnazar**
we need this because without this package we are getting this error on Ubuntu 14.04 LTS.
```shell
The following packages have unmet dependencies:
 tomcat7 : Depends: tomcat7-common (>= 7.0.52-1ubuntu0.3) but it is not going to be installed
```

### CODE REVIEW

**Comment by mfaure** [comment]
Hi @arbabnazar, thank you for your contribution !

I am not sure this package needs explicit requirement as it seems to be grabbed as a dependency.

Here is the command we now use to install needed packages (excerpt from [pre-requisites.sh](https://github.com/Asqatasun/Asqatasun/blob/develop/docker/single-container/pre-requesites.sh) for a fresh Ubuntu 14.04, used for the Docker image)

```sh
sudo apt-get -y --no-install-recommends install \
    wget \
    bzip2 \
    unzip \
    mysql-server \
    libmysql-java \
    tomcat7 \
    libspring-instrument-java \
    xvfb \
    libdbus-glib-1-2 \
    openjdk-7-jre
```

Is your context different from a fresh Ubuntu 14.04 ? 

The documentation on that subject is being rewritten in [/docs/en/10_Install_doc/](https://github.com/Asqatasun/Asqatasun/tree/develop/docs/en/10_Install_doc/Asqatasun), in the `develop` branch. By the way, we use to add every new work / patch / pull request on the `develop` branch, as `master` is the "production" branch. All of that will be explained in a CONTRIBUTING.md file (when it's ready ;) )

Anyway,  to understand why `libtomcat7-java` is not included, could you provide a bit more information on your context ?

**Comment by arbabnazar** [comment]
@mfaure I am using the fresh Ubuntu 14.04 LTS for developing the Ansible role and got this error, by doing some R&D, it turn out that I need to add that pre-req and I did that and error went away, so thought to let the community know about it. If you want me paste the complete trace for error, please let me know. Thanks

**Comment by mfaure** [comment]
@arbabnazar Glad to hear it seems OK for you. 

Yes I would be interested in your trace. Then if everything is OK and if you agree we should close this PR.

**Comment by arbabnazar** [comment]
@mfaure can you please let me know that where I can find the exact version number i.e 1.1.0 etc because I want to use it inside the ansible role instead of mentioning the `latest` word. Thanks.

**Comment by jkowalczyk** [comment]
As you can see, you can get the full list of releases by clicking in the release tab of the github main interface.
By now, there are two releases : v4.0.0-beta1 and v4.0.0-beta2 and we expect to have a a 4.0.0 very soon. 
Hope it helps
Regards, 
Jerome

**Comment by arbabnazar** [comment]
@mfaure here's the error trace. Thanks
```shell
failed: [asqatasun] => (item=wget,bzip2,openjdk-7-jre,unzip,mysql-server,libmysql-java,python-mysqldb,tomcat7,libspring-instrument-java,xvfb,libdbus-glib-1-2,mailutils,postfix) => {"failed": true, "item": "wget,bzip2,openjdk-7-jre,unzip,mysql-server,libmysql-java,python-mysqldb,tomcat7,libspring-instrument-java,xvfb,libdbus-glib-1-2,mailutils,postfix"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tomcat7 : Depends: tomcat7-common (>= 7.0.52-1ubuntu0.3) but it is not going to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'openjdk-7-jre' 'unzip' 'mysql-server' 'libmysql-java' 'python-mysqldb' 'tomcat7' 'libspring-instrument-java' 'xvfb' 'mailutils' 'postfix'' failed: E: Unable to correct problems, you have held broken packages.
```

**Comment by jkowalczyk** [comment]
@arbabnazar 
Is it possible for you to execute a `apt-get update` before performing the installation? 
I tried to install tomcat7 in a fresh instance and I encountered the same problem. 
After having updated `apt-get`, the `tomcat7-common` package is seen as a **NEW package that will be installed**. 
Hope it helps ! 

Regards 
Jerome

**Comment by arbabnazar** [comment]
@jkowalczyk I did the `apt-get update` before installation of these packages but no luck but once, I have added the `libtomcat7-java` package, the error went away. Thanks

**Comment by arbabnazar** [comment]
@mfaure @jkowalczyk  I have added the ansible role inside it, please check it and share it with the community. If you want me to modify it, please let me know. Thanks

**Comment by dzc34** [comment]
@arbabnazar 
your commit "adding the ansible role for asqatasun"
is now in new branch :
https://github.com/Asqatasun/Asqatasun/tree/add_ansible_role_by_arbabnazar

I have not managed to treat your commit "add the libtomcat7-java package"
because documentation much changed in the dev branch and it's not finished yet.

**Comment by arbabnazar** [comment]
closing this PR

**Pull request closed without merging**
